import "./globals.css";
import { Montserrat } from "next/font/google";

import NavBar from "./components/NavBar";

const monserat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monserat.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
